"""LangGraph state models for the agent workflow."""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from app.models.schemas import Message, MessageRole


class AgentRoutingDecision(BaseModel):
    """The orchestrator's decision about which agent should handle the query."""

    agent_type: Literal["travel_support", "booking_payments", "policy"] = Field(
        ...,
        description="The type of agent selected to handle the query",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score of the routing decision (0.0 to 1.0)",
    )
    reasoning: Optional[str] = Field(
        None, description="Brief explanation of why this agent was selected"
    )


class RetrievedContext(BaseModel):
    """Context retrieved from the knowledge base."""

    documents: List[str] = Field(
        default_factory=list,
        description="Retrieved document chunks from vector search",
    )
    metadata: List[dict] = Field(
        default_factory=list,
        description="Metadata associated with retrieved documents",
    )
    agent_type: Optional[str] = Field(
        None, description="The agent type these documents are for"
    )


class CachedData(BaseModel):
    """Session-cached data for agents that use CAG strategy."""

    agent_type: Literal["booking_payments", "policy"] = Field(
        ..., description="The agent type this cache is for"
    )
    documents: List[str] = Field(
        default_factory=list, description="Cached static documents"
    )
    cached_at: Optional[str] = Field(
        None, description="Timestamp when data was cached"
    )


class AgentGraphState(BaseModel):
    """
    LangGraph state model for the multi-agent workflow.

    This state is maintained throughout the agent execution flow and
    contains conversation history, routing decisions, and retrieved context.
    """

    # Conversation history
    messages: List[Message] = Field(
        default_factory=list,
        description="List of messages in the conversation history",
    )

    # Current user query
    current_query: Optional[str] = Field(
        None, description="The current user query being processed"
    )

    # Routing information
    routing_decision: Optional[AgentRoutingDecision] = Field(
        None, description="The orchestrator's routing decision"
    )

    # Retrieved context from knowledge base
    retrieved_context: Optional[RetrievedContext] = Field(
        None, description="Context retrieved from the vector database"
    )

    # Cached data for CAG agents
    cached_data: Optional[CachedData] = Field(
        None,
        description="Cached static documents for agents using CAG strategy",
    )

    # Session management
    session_id: Optional[str] = Field(
        None, description="Session ID for maintaining state across requests"
    )

    # Agent processing info
    current_agent: Optional[str] = Field(
        None,
        description="The agent currently processing the request",
    )

    # Final response
    response: Optional[str] = Field(
        None, description="The final response generated by the agent"
    )

    class Config:
        """Pydantic configuration."""

        arbitrary_types_allowed = True

